from dataclasses import MISSING, dataclass
from enum import Enum
from typing import Any, Callable, ClassVar, Dict, List, Optional, Protocol, TypeVar, Union, runtime_checkable

_T = TypeVar("_T")


class _WithoutDefault:
    pass


WITHOUT_DEFAULT = type(_WithoutDefault())
MISSING_TYPE = type(MISSING)


class Loader(Enum):
    """Config Loader Enums."""

    INI = "from_ini"
    YAML = "from_yaml"
    DICT = "from_dict"
    FILE = "from_file"


@dataclass(frozen=True)
class ConfigOption:
    """Config Option Constants."""

    READ_CONFIG_METHOD: str = "__auto_option_init__"
    ATTRIBUTES: str = "__auto_option_attributes__"
    PASSED_DECORATE_KEY: str = "__auto_option_key__"
    CONFIG_FILE_OPTION_PARAM: str = "config_file"


@dataclass(frozen=True)
class ConfigDecoratorArgs:
    """Config Arguments Arguments."""

    FILES: str = "files"
    SECTIONS: str = "sections"
    USE_REGEX: str = "use_regex"
    IS_LIST: str = "is_list"
    DEFAULT_LOADER: str = "default_loader"
    ALLOW_EMPTY: str = "allow_empty"
    FILTER_FUNCTION: str = "filter_function"


@dataclass(frozen=True)
class ConfigDecorator:
    """Config Decorator Constants."""

    FILES: str = "__config_files__"
    SECTIONS: str = "__config_sections__"
    USE_REGEX: str = "__multi_config__"
    IS_LIST: str = "__config_list__"
    DEFAULT_LOADER: str = "__default_loader__"
    ALLOW_EMPTY: str = "__allow_empty_config__"
    FILTER_FUNCTION: str = "__config_filter_function__"
    CHAIN_FILES: str = "__chain_files__"

    SECTION_NAME_KEY: str = "section_name"


@dataclass(frozen=True)
class DataclassDecorator:
    """Dataclass Decorator Constants."""

    FIELDS: str = "__dataclass_fields__"
    DICT_FACTORY: str = "__dict_factory__"
    TUPLE_FACTORY: str = "__tuple_factory__"
    EVAL_ENV: str = "__eval_env__"
    IGNORED_SLOTS: str = "__ignored_slots__"


@dataclass(frozen=True)
class Constants:
    """Constants."""

    DEFAULT_LOADER: Loader = Loader.INI
    DEFAULT_CONFIG_FILE: str = "config.ini"
    config_option: ConfigOption = ConfigOption
    config_decorator_args: ConfigDecoratorArgs = ConfigDecoratorArgs
    config_decorator: ConfigDecorator = ConfigDecorator
    dataclass_decorator: DataclassDecorator = DataclassDecorator


ConfigArgument = Optional[Optional[Union[Dict[Optional[str], Union[List[str], str]], List[str], str]]]


@runtime_checkable
class LoaderMethod(Protocol):
    """Config loader method protocol."""

    @staticmethod
    def __call__(
        files: ConfigArgument = None,
        sections: ConfigArgument = None,
        keys: ConfigArgument = None,
        defaults: ConfigArgument = None,
        eval_env: bool = False,
        *args,
        **kwargs
    ) -> Any:
        """Config loader method protocol.

        Methods generated by the Methods implemented in:
        from_yaml -> :meth:`cornflakes.decorator.config.yaml.create_yaml_file_loader`
        from_ini -> :meth:`cornflakes.decorator.config.ini.create_ini_file_loader`
        from_dict -> :meth:`cornflakes.decorator.config.dict.create_dict_file_loader`
        """
        ...


@runtime_checkable
class Dataclass(Protocol):
    """Dataclass protocol custom implementation."""

    # stdlib attributes
    __dataclass_fields__: ClassVar[Dict[str, Any]]
    __dataclass_params__: ClassVar[Dict]  # in reality `dataclasses._DataclassParams`
    __annotations__: ClassVar[Dict]
    # _FIELDS: ClassVar[]
    __args__: ClassVar[List[Any]]
    # custom
    __eval_env__: bool = None

    def __post_init__(self, *args, **kwargs):
        """Post init method."""
        ...

    def __call__(self, *args, **kwargs) -> Any:
        """Call Function."""
        ...

    def to_dict(self, *args, **kwargs) -> Any:
        """Parse config to dict.

        Method implemented in :meth:`cornflakes.decorator.dataclass._dataclass.to_dict`.
        """
        ...

    def to_tuple(self, *args, **kwargs) -> Any:
        """Parse config to tuple.

        Method implemented in :meth:`cornflakes.decorator.dataclass._dataclass.to_tuple`.
        """
        ...

    def to_ini(self, *args, **kwargs) -> Optional[bytearray]:
        """Parse config to ini file / bytes.

        Method implemented in :meth:`cornflakes.decorator.config.ini.to_ini`.
        """
        ...

    def to_yaml(self, *args, **kwargs) -> Optional[bytearray]:
        """Parse config to yaml file / bytes.

        Method implemented in :meth:`cornflakes.decorator.config.yaml.to_yaml`.
        """
        ...

    def to_yaml_bytes(self, *args, **kwargs) -> Optional[bytearray]:
        """Parse config to yaml bytes.

        Method implemented in :meth:`cornflakes.decorator.config.yaml.to_yaml_bytes`.
        """
        ...

    def to_ini_bytes(self, *args, **kwargs) -> Optional[bytearray]:
        """Parse config to ini bytes.

        Method implemented in :meth:`cornflakes.decorator.config.ini.to_ini_bytes`.
        """
        ...

    def validate_kwargs(self, validate=False, **kwargs) -> Dict[str, Any]:
        """Validate kwargs.

        Method implemented in :meth:`cornflakes.decorator.dataclass._validate.validate_dataclass_kwargs`.
        """
        ...

    def check_kwargs(self, validate=False, **kwargs) -> Dict[str, Any]:
        """Check dataclass kwargs.

        Method implemented in :meth:`cornflakes.decorator.dataclass._validate.check_dataclass_kwargs`.
        """
        ...


@runtime_checkable
class Config(Protocol):
    """Config Protocol Type."""

    # stdlib attributes
    __dataclass_fields__: ClassVar[Dict[str, Any]]
    __dataclass_params__: ClassVar[Dict]  # in reality `dataclasses._DataclassParams`
    __annotations__: ClassVar[Dict]
    __post_init__: ClassVar[Optional[Callable[..., None]]]
    # _FIELDS: ClassVar[]
    __args__: ClassVar[List[Any]]
    # custom
    __eval_env__: bool = None

    __config_sections__: ClassVar[ConfigArgument]
    __config_files__: ClassVar[ConfigArgument]
    __ignored_slots__: ClassVar[List[str]]
    __multi_config__: ClassVar[bool]
    __config_list__: ClassVar[bool]
    __chain_files__: ClassVar[bool]
    __allow_empty_config__: ClassVar[bool]

    def __call__(self, *args, **kwargs) -> Union[Dataclass, Any]:
        """Call Function."""
        ...

    def __config_filter_function__(self) -> bool:
        """Callback function to filter config."""
        ...

    def to_dict(self, *args, **kwargs) -> Any:
        """Parse config to dict.

        Method implemented in :meth:`cornflakes.decorator.dataclass._dataclass.to_dict`.
        """
        ...

    def to_tuple(self, *args, **kwargs) -> Any:
        """Parse config to tuple.

        Method implemented in :meth:`cornflakes.decorator.dataclass._dataclass.to_tuple`.
        """
        ...

    def to_ini(self, *args, **kwargs) -> Optional[bytearray]:
        """Parse config to ini file / bytes.

        Method implemented in :meth:`cornflakes.decorator.config.ini.to_ini`.
        """
        ...

    def to_yaml(self, *args, **kwargs) -> Optional[bytearray]:
        """Parse config to yaml file / bytes.

        Method implemented in :meth:`cornflakes.decorator.config.yaml.to_yaml`.
        """
        ...

    def to_yaml_bytes(self, *args, **kwargs) -> Optional[bytearray]:
        """Parse config to yaml bytes.

        Method implemented in :meth:`cornflakes.decorator.config.yaml.to_yaml_bytes`.
        """
        ...

    def to_ini_bytes(self, *args, **kwargs) -> Optional[bytearray]:
        """Parse config to ini bytes.

        Method implemented in :meth:`cornflakes.decorator.config.ini.to_ini_bytes`.
        """
        ...

    def validate_kwargs(self, validate=False, **kwargs) -> Dict[str, Any]:
        """Validate kwargs.

        Method implemented in :meth:`cornflakes.decorator.dataclass._validate.validate_dataclass_kwargs`.
        """
        ...

    def check_kwargs(self, validate=False, **kwargs) -> Dict[str, Any]:
        """Check dataclass kwargs.

        Method implemented in :meth:`cornflakes.decorator.dataclass._validate.check_dataclass_kwargs`.
        """
        ...

    from_ini: LoaderMethod
    from_yaml: LoaderMethod
    from_dict: LoaderMethod
    from_file: LoaderMethod


@runtime_checkable
class ConfigGroup(Protocol):
    """ConfigGroup Protocol Type."""

    # stdlib attributes
    __dataclass_fields__: ClassVar[Dict[str, Any]]
    __dataclass_params__: ClassVar[Dict]  # in reality `dataclasses._DataclassParams`
    __annotations__: ClassVar[Dict]
    __post_init__: ClassVar[Optional[Callable[..., None]]]
    # _FIELDS: ClassVar[]
    __args__: ClassVar[List[Any]]
    # custom
    __eval_env__: bool = None

    __config_files__: ClassVar[ConfigArgument]
    __multi_config__: ClassVar[bool]
    __config_list__: ClassVar[bool]
    __chain_files__: ClassVar[bool]
    __allow_empty_config__: ClassVar[bool]

    def __call__(self, *args, **kwargs) -> Union[Dataclass, Any]:
        """Call Function."""
        ...

    def __config_filter_function__(self) -> bool:
        """Callback function to filter config."""
        ...

    def to_dict(self, *args, **kwargs) -> Any:
        """Parse config to dict.

        Method implemented in :meth:`cornflakes.decorator.dataclass._dataclass.to_dict`.
        """
        ...

    def to_tuple(self, *args, **kwargs) -> Any:
        """Parse config to tuple.

        Method implemented in :meth:`cornflakes.decorator.dataclass._dataclass.to_tuple`.
        """
        ...

    def to_ini(self, *args, **kwargs) -> Optional[bytearray]:
        """Parse config to ini file / bytes.

        Method implemented in :meth:`cornflakes.decorator.config.ini.to_ini`.
        """
        ...

    def to_yaml(self, *args, **kwargs) -> Optional[bytearray]:
        """Parse config to yaml file / bytes.

        Method implemented in :meth:`cornflakes.decorator.config.yaml.to_yaml`.
        """
        ...

    def to_yaml_bytes(self, *args, **kwargs) -> Optional[bytearray]:
        """Parse config to yaml bytes.

        Method implemented in :meth:`cornflakes.decorator.config.yaml.to_yaml_bytes`.
        """
        ...

    def to_ini_bytes(self, *args, **kwargs) -> Optional[bytearray]:
        """Parse config to ini bytes.

        Method implemented in :meth:`cornflakes.decorator.config.ini.to_ini_bytes`.
        """
        ...

    def validate_kwargs(self, validate=False, **kwargs) -> Dict[str, Any]:
        """Validate kwargs.

        Method implemented in :meth:`cornflakes.decorator.dataclass._validate.validate_dataclass_kwargs`.
        """
        ...

    def check_kwargs(self, validate=False, **kwargs) -> Dict[str, Any]:
        """Check dataclass kwargs.

        Method implemented in :meth:`cornflakes.decorator.dataclass._validate.check_dataclass_kwargs`.
        """
        ...

    from_ini: LoaderMethod
    from_yaml: LoaderMethod
    from_dict: LoaderMethod
    from_file: LoaderMethod
