"""Automatically generated Default Config.

!!!This files is autogenerated, please do not modify manually.!!!
!!!Change the file default-htw-logger.ini or the default values in the base-classes of htw_logger.config!!!
!!!IF htw_logger.config not exists run ```make install``` before!!!
"""

from cornflakes import config_group
from tests.configs.sub_config import SubConfig


@config_group(files=["tests/configs/default.ini"], eval_env=True)
class MainConfig:
    """Main config class of the module."""


__all__ = ["MainConfig"]
