"""Automatically generated Default Config.

!!!This files is autogenerated, please do not modify manually.!!!
!!!Change the file default-htw-logger.ini or the default values in the base-classes of htw_logger.config!!!
!!!IF htw_logger.config not exists run ```make install``` before!!!
"""
from dataclasses import dataclass
from decimal import Decimal

from cornflakes import add_slots
from cornflakes.decorator import ini_config

# import config


@ini_config
@add_slots
@dataclass(frozen=True)
class Config:
    """Main config class of the module."""

    pass


def crate_config() -> Config:
    """Method to create a instance of the main config class of the module."""
    pass


__all__ = ["Decimal", "crate_config", "Config"]
