name: Build cornflakes Package

on: [push, pull_request]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
        strategy:
            matrix:
                os: [macos-10.15, ubuntu-latest, windows-latest]
                python: ["3.8", "3.9", "3.10", "3.11"]

        steps:
            - uses: actions/checkout@v3.3.0
              with:
                  remote: true
                  submodules: recursive
              name: Check out source-code repository

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python }}

            - name: Install Poetry
              run: |
                  pip install poetry
                  poetry --version

            - name: Install Ninja
              run: |
                  pip install ninja
                  ninja --version

            - name: Build package
              run: poetry build --ansi

            - name: Install required twine packaging dependencies
              run: pip install setuptools wheel twine

            - name: Check twine package
              run: twine check dist/*

    build_many_linux:
        runs-on: ${{ matrix.os }}
        if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
        container:
            image: quay.io/pypa/manylinux_2_28_x86_64:latest
        strategy:
            matrix:
                os: [ubuntu-latest]
                python: ["3.8", "3.9", "3.10", "3.11"]

        steps:
            - uses: actions/checkout@v3.3.0
              with:
                  remote: true
                  submodules: recursive
              name: Check out source-code repository

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python }}

            - name: Install Poetry
              run: |
                  pip install poetry
                  poetry --version

            - name: Install Ninja
              run: |
                  pip install ninja
                  ninja --version

            - name: Install required twine packaging dependencies
              run: pip install setuptools wheel twine

            - name: Build package
              run: poetry build

            #            - uses: RalfG/python-wheels-manylinux-build@v0.7.1
            #              with:
            #                  python-versions: "cp38-cp38 cp39-cp39 cp310-cp310 cp311-cp311"

            - name: Check twine package
              run: twine check dist/*
