name: Build cornflakes Package

on: [push, pull_request]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
        strategy:
            matrix:
                os:
                    - name: freebsd
                      architecture: x86-64
                      version: "13.0"
                      host: macos-12

                    - name: openbsd
                      architecture: x86-64
                      version: "7.1"
                      host: macos-12

                    - name: openbsd
                      architecture: arm64
                      version: "7.1"
                      host: ubuntu-latest

                    - name: netbsd
                      architecture: x86-64
                      version: "9.2"
                      host: ubuntu-latest
                      python: ["3.8", "3.9", "3.10", "3.11"]

                    - [windows-latest, macos-latest]

                python: ["3.8", "3.9", "3.10", "3.11"]

        steps:
            - uses: actions/checkout@v3.1.0
              with:
                  remote: true
                  submodules: recursive
              name: Check out source-code repository

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python }}

            - name: Install Poetry
              run: |
                  pip install poetry
                  poetry --version

            - name: Install Ninja
              run: |
                  pip install ninja
                  ninja --version

            - name: Build package
              run: poetry build --ansi

            - name: Install required twine packaging dependencies
              run: pip install setuptools wheel twine

            - name: Check twine package
              run: twine check dist/*
