name: Labeler

on:
    push:
        branches:
            - main
            - master

jobs:
    labeler:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repository
              uses: actions/checkout@v3
              with:
                  remote: true
                  submodules: recursive

            - name: Run Labeler
              uses: crazy-max/ghaction-github-labeler@v4.0.0
              with:
                  skip-delete: true
