name: Build Documentation

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              name: Check out source-code repository

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.8

            - name: Install doxygen
              run: |
                  sudo apt-get install -y doxygen

            - name: Install pip
              run: |
                  python -m pip install --upgrade pip

            - name: Install Poetry
              run: |
                  source ./venv/bin/activate
                  pip install poetry
                  poetry --version

            - name: Install Ninja
              run: |
                  source ./venv/bin/activate
                  pip install ninja
                  ninja --version

            - name: Install doc dependencies
              run: |
                  make install

            - name: Build docs
              run: |
                  cd docs
                  make html

            - name: Deploy
              if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'}}
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs/_build/html
