name: Publish cornflakes to PyPI

on:
    release:
        types: [published]

jobs:
    release:
        name: Release
        runs-on: ${{ matrix.os }}
        if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
                python: ["3.8", "3.9", "3.10", "3.11"]
        steps:
            - name: Check out the repository
              uses: actions/checkout@v3.6.0
              with:
                  fetch-depth: 2
                  remote: true
                  submodules: recursive

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python }}

            - name: Install Ninja
              run: |
                  pip install ninja
                  ninja --version

            - name: Install Poetry
              run: |
                  pip install poetry
                  poetry --version

            - name: Install Twine
              run: |
                  pip install twine

            - name: Build package
              run: |
                  poetry build --ansi

            # Build and upload to PyPI
            - name: "Builds and uploads to PyPI"
              run: |
                  python -m twine upload dist/* --skip-existing
              env:
                  TWINE_USERNAME: __token__
                  TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
    #            - name: Publish package on PyPI
    #              uses: pypa/gh-action-pypi-publish@v1.5.1
    #              with:
    #                  skip_existing: true
    #                  # https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
    #                  user: __token__
    #                  password: ${{ secrets.PYPI_TOKEN }}

    release_manylinux_2_28_x86_64:
        runs-on: ${{ matrix.os }}
        if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
        container:
            image: quay.io/pypa/manylinux_2_28_x86_64:latest
        strategy:
            matrix:
                os: [ubuntu-latest]
                python: ["3.8", "3.9", "3.10", "3.11"]

        steps:
            - uses: actions/checkout@v3.6.0
              with:
                  remote: true
                  submodules: recursive
              name: Check out source-code repository

            - name: Setup Python
              run: |
                  python${{ matrix.python }} -m pip install --upgrade pip
                  python${{ matrix.python }} -m pip install virtualenv
                  python${{ matrix.python }} -m venv ./venv
                  source ./venv/bin/activate

            - name: Install Poetry
              run: |
                  source ./venv/bin/activate
                  pip install poetry
                  poetry --version

            - name: Install Ninja
              run: |
                  source ./venv/bin/activate
                  pip install ninja
                  ninja --version

            - name: Install required twine packaging dependencies
              run: |
                  source ./venv/bin/activate
                  pip install setuptools wheel twine auditwheel

            - name: Build package
              run: |
                  source ./venv/bin/activate
                  poetry build --ansi

            # Build and upload to PyPI
            - name: "Builds and uploads to PyPI"
              run: |
                  source ./venv/bin/activate
                  python -m auditwheel repair $(ls dist/*.whl)
                  python -m twine upload $(ls wheelhouse/*.whl)  --skip-existing --verbose
              env:
                  TWINE_USERNAME: __token__
                  TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}

    release_manylinux2014_x86_64:
        runs-on: ${{ matrix.os }}
        if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
        container:
            image: quay.io/pypa/manylinux2014_x86_64:latest
        strategy:
            matrix:
                os: [ubuntu-latest]
                python: ["3.8", "3.9", "3.10", "3.11"]

        steps:
            - uses: actions/checkout@v3.6.0
              with:
                  remote: true
                  submodules: recursive
              name: Check out source-code repository

            - name: Setup Python
              run: |
                  python${{ matrix.python }} -m pip install --upgrade pip
                  python${{ matrix.python }} -m pip install virtualenv
                  python${{ matrix.python }} -m venv ./venv
                  source ./venv/bin/activate

            - name: Install Poetry
              run: |
                  source ./venv/bin/activate
                  pip install poetry
                  poetry --version

            - name: Install Ninja
              run: |
                  source ./venv/bin/activate
                  pip install ninja
                  ninja --version

            - name: Install required twine packaging dependencies
              run: |
                  source ./venv/bin/activate
                  pip install setuptools wheel twine auditwheel

            - name: Build package
              run: |
                  source ./venv/bin/activate
                  poetry build --ansi

            # Build and upload to PyPI
            - name: "Builds and uploads to PyPI"
              run: |
                  source ./venv/bin/activate
                  python -m auditwheel repair $(ls dist/*.whl)
                  python -m twine upload $(ls wheelhouse/*.whl)  --skip-existing --verbose
              env:
                  TWINE_USERNAME: __token__
                  TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
#    release_manylinux2014_aarch64:
#        runs-on: ${{ matrix.os }}
#        if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
#        container:
#            image: quay.io/pypa/manylinux2014_aarch64:latest
#        strategy:
#            matrix:
#                os: [ubuntu-latest]
#                python: ["3.8", "3.9", "3.10", "3.11"]
#
#        steps:
#            - name: Run build
#              run: |
#                  git clone https://github.com/semmjon/cornflakes.git --recursive
#                  cp -r ./cornflakes .
#                  python${{ matrix.python }} -m pip install --upgrade pip
#                  python${{ matrix.python }} -m pip install virtualenv
#                  python${{ matrix.python }} -m venv ./venv
#                  source ./venv/bin/activate
#                  pip install poetry
#                  poetry --version
#                  pip install ninja
#                  ninja --version
#                  pip install setuptools wheel twine auditwheel
#                  poetry build --ansi
#                  python -m auditwheel repair $(ls dist/*.whl)
#                  python -m twine upload $(ls wheelhouse/*.whl)  --skip-existing --verbose
#              env:
#                  PYTHONPATH: /app
#                  TWINE_USERNAME: __token__
#                  TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
